### PR TITLE
Enforce not following redirects

### PR DESCRIPTION
**Pull request by kamaradclimber**
(note I have made this depend on my previous PR but can change it if necessary)

### CODE REVIEW

**Comment by stevenschlansker** [comment]
This change looks okay, but I cannot merge the previous change as I commented in the other issue.
Either we can hold this until we resolve the other one, or you can rebase this single commit to master.

**Comment by kamaradclimber** [comment]
From a mesos cluster in 0.22, I got the http:// prefix. On my more recent cluster (0.23) the prefix is gone.

I guess this is linked to work done for https://issues.apache.org/jira/browse/MESOS-1825 (support of https for the webui) since Location header not starting with a protocol should keep the protocol used before redirection.

I'll modify the patch to support both versions

**Comment by kamaradclimber** [comment]
I've just rebased to ignore my other patch so this one could be merged independantly.

**Comment by stevenschlansker** [comment]
@kamaradclimber Your PRs have been released as 0.2.4

**Comment by kamaradclimber** [comment]
great thanks

**Pull request merged**
