### PR TITLE
Fix master redirect

### PR DESCRIPTION
**Pull request by kamaradclimber**
Location header starts with //[master] instead of http://

### CODE REVIEW

**Comment by stevenschlansker** [comment]
Hi, I do not see this problem at all:

```
[steven@Anesthetize:~]% curl -v http://mesos1-qa-uswest2.mycorp.com:5050/master/redirect
> GET /master/redirect HTTP/1.1
> User-Agent: curl/7.30.0
> Host: mesos1-qa-uswest2.otenv.com:5050
> Accept: */*
> 
< HTTP/1.1 307 Temporary Redirect
< Date: Fri, 04 Sep 2015 19:57:09 GMT
< Location: http://mesos1-qa-uswest2.qasql.opentable.com:5050
< Content-Length: 0
< 
* Connection #0 to host mesos1-qa-uswest2.otenv.com left intact
```

Could you provide some more information about your environment?  Maybe this is a Mesos version difference?  Merging this change as-is will break it for us.

**Comment by kamaradclimber** [comment]
Thanks for your feedback.
I am using mesos 0.23, I'll provide more information on Monday when I'll be at work.

**Comment by kamaradclimber** [comment]
From a mesos cluster in 0.22, I got the http:// prefix. On my more recent cluster (0.23) the prefix is gone.

I guess this is linked to work done for https://issues.apache.org/jira/browse/MESOS-1825 (support of https for the webui) since Location header not starting with a protocol should keep the protocol used before redirection.

I'll modify the patch to support both versions

**Comment by kamaradclimber** [comment]
I've pushed another patch to make it work with both mesos versions

**Pull request merged**
